### ISSUE TITLE
sprint1_major - скорректировать текст письма

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#110]
text

Email Confirmation

We see you have registered an account on Ursas Planet, Welcome!

Please use the following code to verify your email:

083337

Have a nice day!

**Comment by hoolisoftware** [comment]
![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/64575343/67fa4126-471c-466c-b0e7-55bcdc998d38)
