### ISSUE TITLE
major - добавить иконки сетей + иконку неверной сети (p.s. заменить эфир на полигон)

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#119]
Добавить иконки сетей ETH, BNB, ARB - больше пока не нужно
удалить иконку собаки
(добавить иконку в случае неверной сети)

![image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/b7b1326c-a9ff-45cb-8351-d2c178bdfe4a)
![image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/f11790b9-94fb-4f30-aac9-c6e9ad10da03)

**Comment by hoolisoftware** [comment]
В макете не нашёл иконку eth, пока оставил иконку polygon вместо eth

**Comment by bageus** [comment]
да  нужно поправить eth на полигон

**Comment by bageus** [comment]
еще в самом кошельке странные иконки сетей, этим мы управляем или это метамаск?

![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/2e33f824-8122-4bba-9117-c30474014924)

**Comment by hoolisoftware** [comment]
да, это я вроде настраивал :) я не заметил этого

**Comment by hoolisoftware** [comment]
Пробовал на сайте chainlist добавить сеть, там теже самые картинки даёт. Получается не можем менять.

**Comment by bageus** [comment]
осталось поменять эфириум на полигон
