### ISSUE TITLE
major- сверстать блоки для upcoming, last и разных призов

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#121]
![image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/cc627708-971f-479c-bf24-091af5bc3f18)

**Comment by hoolisoftware** [comment]
В чём разница этих блоков, по сути меняется же только изображение и метрики приза?

**Comment by bageus** [comment]
да, меняются только метрики, смысл в том что из блокчейна в зависимости от типа приза будет подтягиваться информация по метрикам, метрики немного отличаются и отображение их тоже, поэтому я и прошу сверстать несколько вариантов

**Comment by hoolisoftware** [comment]
Где достать метрики и картинку приза которые нужно отображать в зависимости от выбранного сезона (upcoming, current etc.)

**Comment by bageus** [comment]
метрики будут из контракта подтягиваться, изображение нфт тоже из контракта, монеты у нас пока только матик будет, его изображение приложил, wl - тоже приложил

**Comment by bageus** [comment]
![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/6fc9a060-43b3-4633-a725-5711cd13fb72)



![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/203181c5-116c-4e7e-a5fa-7d86c723d27a)

**Comment by bageus** [comment]
не получилось как в макете сделать?
там и цвет другой и уже она

![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/a1170a76-e940-4d36-9c27-4efae07f29f6)

**Comment by bageus** [comment]
как то криво все смотрится - попробуй по этим строкам разнести элементы


![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/5c48489c-30a8-4f57-bc99-ea5826801533)

**Comment by bageus** [comment]
или так, нужна какая то симметрия 


![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/b708b9f7-14db-4bbe-9fa2-6ed14a5c6af4)
