### ISSUE TITLE
major- если у пользователя нет согласованного проекта кнопку project нужно немного затемнить

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#124]
![image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/57db63c8-1313-4c32-acd3-585a63139dc3)

**Comment by bageus** [comment]
я просто хочу что бы эта механика работала

**Comment by hoolisoftware** [comment]
Не думаю что эту механику будет сложно сделать когда в проекте будут проекты) Тем более даже если я попытаюсь эту логику реализовать как её можно будет проверить?

**Comment by hoolisoftware** [comment]
![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/64575343/97382a6a-4b90-483f-93f3-027767f83a85)
