### ISSUE TITLE
Если кошелёк не подключен предлагается к кнопкам Player и Project привязать модалку подключения кошелька

### ISSUE THREAD

**Issue by hoolisoftware** [JUSTConnect/ursus-planet-client#129]
![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/64575343/cc046497-f28f-403e-95a8-20f35cc4692e)

**Comment by bageus** [comment]
я думал про это но решил что оставляем пока так как есть, нужно это поюзать что бы понять как лучше
