### ISSUE TITLE
Fix: Сделать разные скелетоны

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#133]
Сделать скелетоны под **текст**, **кнопку**, **инпут** и **блок**.

Комментарий заказчика:

"**может есть другие скелетоны, или выровнять их между собой, и сделать тусклее , а то они бросаются в глаза сильно:**
![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/c586a642-a174-48d7-b2da-b736b05aa0e5)"

**Comment by bageus** [comment]
все равно они мне не нравятся

**Comment by hoolisoftware** [comment]
Можете вектор задать?

**Comment by hoolisoftware** [comment]
Перенесли в след спринт
