### ISSUE TITLE
Feature: Реализовать реферальную систему

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#155]
Наводка заказчика:
**формировать как ссылки так и коды
код = username
логика по кол-ву приглашенных, 
изначально доступно 30 инвайтов в день
далее при общем количестве рефералов более 30 - количество дневных инвайтов = количеству тотал рефералов.
если дневной лимит превышен - рефералы не засчитываются 

нужно понять на сколько это проблемно сделать и есть ли смысл в ограничениях**

**Comment by hoolisoftware** [comment]
Предлагаю userflow:
1) Пользователь заходит в `Point system/Referral codel`
2) Нажимает на поле `Enter referral code`
3) В модалке вводит username своего реферала (Если введён несуществующий username, выводится сообщение "Invalid username", если введён username у которого дневной лимит заполнен, выводится ошибка "This user exceed daily limit of referrals, please try again tomorrow.")
4) Если введён велидный username, модалка закрыватеся и карточка `Referral code` изменяется на 
![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/64575343/1f9244e3-18f7-4e98-b011-1cb639e56758)

 

Вопросы:
1) Задания "Реферрера" и "Реферрала" не включены в спринт, можем их тоже добавить

**Comment by bageus** [comment]
Конечно нужно добавить, я поэтому и описывал все в одной задаче, по сути это задание с рефералом засчитывается на вкладке referrals
