### ISSUE TITLE
major - при выборе роли проекта до подключения кошелька выводить сообщение о том что у пользователя отсутвует проект

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#165]
После подключения кошелька выводить сообщение:

"ООps..!! It looks like you don't have an approved project yet, but you were connected as a player."

![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/64575343/217e5018-c28a-467a-aeb8-039bddd691f8)

P.S. Никакой дополнительной логики не предполагается.

**Comment by hoolisoftware** [comment]
Нужны подробности.

**Comment by bageus** [comment]
когда подключаешь кошелек через роль 
может быть несколько вариантов 
- у игрока нет согласованного проекта - показываем после подключения кошелька "ООps..!! It looks like you don't have an approved project yet, but you were connected as a player." - подключаем в роли игрока
- у игрока есть согласованный проект, но подключился он кошельком игорока а не проекта - показываем после подключения кошелька "Welcome! Please use the project management wallet, but you were connected as a player." - подключаем в роли игрока
- у игрока есть согласованный проект и для управления проектом используется используется кошелек игрока  - подключаем в роли проекта
- у пользователя есть согласованный проект для подключения используется кошелек проекта - подключаем в режиме проекта

по размещению сообщения нужно подумать где его лучше разместить
 
![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/afcb52ab-881e-4b28-8c61-c803fe32b737)

**Comment by hoolisoftware** [comment]
Давайте пока каждый раз после того как юзер логинится выводить это сообщение.

Когда появятся проекты подкорректируем.

**Comment by bageus** [comment]
ок, только вопрос куда его поместить

**Comment by hoolisoftware** [comment]
это уже к вам вопрос. я не понимаю зачем оно нужно. если укажите больше деталей...

**Comment by hoolisoftware** [comment]
Зарисуйте это сообщение в макете. Или мне симпровизировать это сообщение?

**Comment by bageus** [comment]
я то могу зарисовать - просто такие системные мообщения у нас еще будут и нужно какое то общее решение по тому где и как они будут появляться, ты говорил про тостер, но по реализации там какие то траблы как я понял, что еще можно придумать?

**Comment by hoolisoftware** [comment]
Можем сделать вот такой тостер, в соответствии с общим дизайном сайта.

https://www.radix-ui.com/primitives/docs/components/toast

**Comment by bageus** [comment]
ок
