### ISSUE TITLE
Добавить иконку  при подключении кошелька в метамаск

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#166]
В тот момент когда пользователь подтверждает подключение кошелька должна появляться иконка в указанном месте:

![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/64575343/d944b4f2-8fd3-4684-960c-de502fefdde0)

**Comment by hoolisoftware** [comment]
Нужны подробности, можете указать на макет.

**Comment by bageus** [comment]
в макете этого нет, это происходит в модалке кошелька, при подключении к сайту, когда подключаешь обрати внимание

**Comment by hoolisoftware** [comment]
Вы про надпись "Connecting..."? Если нет скиньте скрин с пометкой.

**Comment by bageus** [comment]
Да когда идет connecting, я не успеваю его словить что бы скрин отправить, там как бы есть иконка, но она как то криво отображается, на весь объем забирает

**Comment by hoolisoftware** [comment]
Какую именно иконку туда добавить, можете хотя бы пометить на самой модалке.

**Comment by hoolisoftware** [comment]
Какую иконку добавить?

**Comment by bageus** [comment]
ту же что и фавиконе

**Comment by bageus** [comment]
не появилась

**Comment by hoolisoftware** [comment]
хорошо приглянитесь в начала она мерцает и резко изчезает, почему то у меня на других сайтах аналогичная ситуация

потому что я сделал всё по документации, и даже если бы сделал не правильно она бы там вообще не появлялась (даже и мерцанием).

**Comment by bageus** [comment]
![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/223bc103-fa0d-4fcd-8a06-b61ec659b09a)
