### ISSUE TITLE
major- исключить возможность добавлять username

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#169]
username
unknown
ursas
ursasplanet
ursas_planet
teddy
teddy_ursas
teddy_ar
teddy_arr
teddy_arrr

**Comment by hoolisoftware** [comment]
Насчёт username понятно, а вот в случае префиксов я предлагаю поставить регулярное выражение - типа юзернейм не может начинаться с ursas- или teddy-.

**Comment by bageus** [comment]
тут думаю это не нужно - потому что нет ничего такого если будет ursas-holder и т.д
