### ISSUE TITLE
Хедер - скрыть или сделать неактивной кнопку уведомлений

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#170]
![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/a94344b0-5a25-4a0b-90e4-4478d95fc9fc)

**Comment by hoolisoftware** [comment]
Вы попросили при нажатии на кнопку показывать что у пользователя 0 уведомлений. То есть всё таки кнопку нужно оставить активной?

**Comment by bageus** [comment]
оставляй, просто из-за разных версий, в кнопке то есть текст то его нет, так как сейчас вполне подходит
