### ISSUE TITLE
major - тут что то на непонятном

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#173]
и форму для ввода почты тоже нужно проверить

![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/8ce9db76-2d58-45ff-8c95-faf604500d68)

**Comment by hoolisoftware** [comment]
Жду подробностей?

**Comment by hoolisoftware** [comment]
Если вы про то что там сообщение на русском языке выскакивает, то это язык браузера (у кого какой язык установлен, на том языке и получает)
