### ISSUE TITLE
Анимация начисления поинтов

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#177]
можем начислять поинты с небольшой задержкой 1-2 секунды и сделать анимацию на цифры что бы было видно как они начисляюятся по 1 но это начисление происходило примерно в течении секунды

![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/4cdbcc30-e32e-4747-827f-964ac83712ec)

**Comment by hoolisoftware** [comment]
Обсудим в след спринте, пока не могу придумать элегантное решение которое не создаст много зависимостей.

**Comment by hoolisoftware** [comment]
Закинул на домен `sprint` вариант анимации с использованием сторонней библиотеки. Правда у неё есть ньюанс: Работает нормально, если не менять ширину экрана (баг срабатывает именно при переходе вёрстки в мобильную версию, `468px` и обратно), в противном случае циферки начинают плыть вниз-вверх.

Если это недопустимо, можно написать свою анимацию по [образцу](https://css-tricks.com/animating-number-counters/).

Вам решать, оставить красивую анимацию закрыв глаза на баг, либо написать свою. 

P.S. Нужно ещё понимать что библиотеки это всегда зависимости и нагрузка на браузер, для подобных мелочей я рекомендую писать самим.

**Comment by bageus** [comment]
оставляй так
