### ISSUE TITLE
major- почему текст на руском?

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#192]
![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/f4d3fe75-886d-4e04-b9b4-a76786e48d63)

**Comment by hoolisoftware** [comment]
это текст браузера он автоматом ставит выбранный язык пользователя

**Comment by hoolisoftware** [comment]
можно конечно и это взять под контроль, правда это займёт время протестить
