### ISSUE TITLE
Проблема - Адрес кошелька в таблице лидерборда

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#198]
![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/06f3d362-3e16-455f-a77d-8d32cdcc73f3)

jor -

**Comment by hoolisoftware** [comment]
дело в том что я для простоты поставил туда adminhash вместо кошелька, который нужен для тестов (postman)
