### ISSUE TITLE
major- main page - все еще виден силуэт снизу

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#2]
![Uploading изображение.png…]()

**Comment by hoolisoftware** [comment]
Пропало изображение

**Comment by bageus** [comment]
это про фигурки - у них видны силуэты снизу и сбоку (сторона тени)

**Comment by hoolisoftware** [comment]
Отправьте изображение для точности

**Comment by bageus** [comment]
выше это же изображение на главной странице нужно заблюрить фигуру внизу

![Image](https://github.com/hoolisoftware/ursus-planet/assets/36338626/1c047702-130c-4165-bfe4-de6a6bab5b21)
