### ISSUE TITLE
Проблема - Реферральный код

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#203]
Запретить менять дважды имя пользователя. В угоду реферальной системе.

**Comment by hoolisoftware** [comment]
какую логику обсудили так и постарался сделать, могу переделать, но отдельно.

**Comment by hoolisoftware** [comment]
Подробнее объясните суть проблемы и возможные предложения.

**Comment by bageus** [comment]
это вроде и не проблема, просто если я сперва укажу одно имя а потом его поменяю, то реферальный код останется по прежнему имени, может это и не проблема, но мне кажется какое то тонкое место - может просто запретить смену имени- устанавливается 1 раз и на всегда

**Comment by hoolisoftware** [comment]
Ну мы можем:
- сделать что бы в качестве реферрального кода оставалось только первое имя навсегда
-  запретить смену username (как и вы написали)

**Comment by bageus** [comment]
давай сделаем так пока идет поинт программа - запретим смену имени, а потом подумаем.
еще вопрос как будет прописываться логика если имя будет выбранно из валлет domain_ID

и вот сюда галочка нужна

![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/2f9bb58e-0072-45f2-8e1d-b921ccfdd950)

**Comment by hoolisoftware** [comment]
Насчёт domain_id если честно я пока без понятия какой там прикладной функционал, поэтому не могу сказать.

Единственное могу заметить что будет у пользователя новое поле "uses domain id as a username" и если оно выбрана, этот domain id на фронте будет браться либо из смарт-контракта постоянно, либо единыжды записывать в бек под ещё одним полем "domain id username".

**Comment by bageus** [comment]
ладно  криптофронтенд вроде как на этой неделе уже начнут делать, за одно как напишем тз станет понятно что делать с domain_ID и формированием реф кода в таком случае,
