### ISSUE TITLE
major - нужно продлить список и отображать справа бар прокрутки

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#205]
![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/0372193b-9c50-4666-a9dc-b6f3c1662e0e)

**Comment by hoolisoftware** [comment]
Можно подробнее, не ясна формулировка.

P.S. Бар я сделал, он появляется когда таблица превышает заданную высоту.
