### ISSUE TITLE
Учесть замечания по системе заданий проектов #2

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#209]
Connect - видна если не подключена соц. сеть при нажати на кнопку выползает коннектор
Follow - если задание подписка на канал, сервер, аккаунт
Do it - для заданий которые невозможно описать

![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/aa53772b-a725-4a54-93b0-9ffe4c7a8d4c)

**Comment by hoolisoftware** [comment]
Задача переформулирована - https://github.com/orgs/JUSTConnect/projects/1/views/9?pane=issue&itemId=54432240

- Если вас устраивает формулировка, перенесите текущую задачу в "Done" а новую задачу пометьте как "Waiting for developer".

- Если не устраивает формулировка, обе задачи пометьте как "Waiting for developer"
