### ISSUE TITLE
Замечания по системе заданий проектов 1

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#211]
- задание может иметь экспирацию а может не иметь, так же имеется возможность в админке завершить задание, в списке отображается как expired
- если задание удалили в админке в списке оно не отображается
- если задание expired но пользователь его успел выполнить в  списке отображается как done
- по разбитию на группы - думаю условно можно заложить сортировку - сперва идут всегда задания Х потом Disc, Telega, Git
- на бекенде должна быть реализована админка

не могу определиться какой из вариантов использовать, лучше отталикиваться от того какой проще в реализации
![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/bd4577fa-a377-4b28-9129-d2c7e4cb052c)

![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/a723dfbe-7936-400c-910e-6a8f2ec0d631)

![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/5cd5dc48-b1a6-46bc-b32f-7ea5c0741d22)

Х - задания

![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/33f0ae0f-3aec-4e00-8ccb-afdbb6cf14b6)

**Comment by hoolisoftware** [comment]
Получается: 
- к модели задач проекта добавить поле "Expiration datetime".
- если задание Expired, но пользователь его выполнил, начислить баллы и пометить как done

---

Задача группировки заданий проектов вынесена в [отдельный таск](https://github.com/orgs/JUSTConnect/projects/1/views/9?pane=issue&itemId=54435813).

---

p.s. Вы уверены что такой формат отображения - это хорошая идея?

![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/64575343/55621923-27f9-4d25-a02c-b06817b7b800)

Кнопки действий задания итак перегружены :)

**Comment by bageus** [comment]
я не могу пока придумать куда запихнуть этот таймер экспирации

**Comment by hoolisoftware** [comment]
Предлагаю в карточку задачи просто добавить иконку часов (если задача временаая, где я подметил), и что бы при наведении на иконку появлялся тултип: 

![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/64575343/283fde43-34c8-45b4-98e1-a2425b7af934)

В тултипе написать такое: "this task has an expiration date / will expire  <дата окончания или таймер до окончания>"


Вот куда предлагаю добавить иконку:



![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/64575343/6124e290-b9fe-4fcd-97f8-39b165498c4f)

**Comment by bageus** [comment]
ну давай этот тулпит

**Comment by hoolisoftware** [comment]
Можно закрывать здесь?
