### ISSUE TITLE
Реализовать задания Custom

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#215]
Имеет следующие поля:
- Заголовок
- Ссылка
- Награда (поинты)
- Дата-время создания
- Доп описание

Что ещё нужно знать про эти задания:
- Задания никак не проверяется, нужно только перейти по кнопке "do it", которая сразу же сменится на get спустя 5 секунд
- Задания custom пока что сортируем по дате-времени создания (по запросу Вадима)

Мемориалы:

![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/64575343/bf9a07ec-4249-4de9-abb0-1451dc90c3ca)

**Comment by hoolisoftware** [comment]
Изменил описание жду подтверждения. Что бы подтвердить напишите "Подтверждаю" и отметьте задание как "Waiting for developer".

**Comment by bageus** [comment]
подтверждаю

**Comment by bageus** [comment]
Имеет следующие поля:

    Заголовок
    Ссылка
    Награда (поинты)
    экспирация
    доп описание

**Comment by bageus** [comment]
фейк способ проверки 
при нажатии на кнопку do it открывается новая страница с соцсетью - с задержкой в 5-60 сек(случайное значение) появляется кнопка get

**Comment by bageus** [comment]
может добавить какой то пендинг на этой кнопке

**Comment by bageus** [comment]
нужно сделать экспирацию как опцию, т.е если включена то нужно заполнять и поле описание и сроки

![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/b72448ec-b090-4d8e-bc80-e206e2713b9e)

**Comment by hoolisoftware** [comment]
is_active если пометить как false скрывает задание из списка
