### ISSUE TITLE
Отображение кнопок задания проекта

### ISSUE THREAD

**Issue by hoolisoftware** [JUSTConnect/ursus-planet-client#217]
Do it - Если задния не выполнено
Get - Если задание выполнено
Done - Если задание выполнено и получена награда

Мемориалы:

![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/64575343/2c008167-0e5c-4894-86f9-4d8e3e0a4c64)

![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/64575343/b246a9df-e6b1-4c21-90cb-630bf19c53bc)

**Comment by hoolisoftware** [comment]
Вы писали про кнопку `do it`: 

![image](https://github.com/JUSTConnect/ursus-planet-client/assets/64575343/221d39f8-e347-494f-b863-61c8936e71c8)

Я так понял, мне нужно рандомно через от 5 до 60 секунд эту кнопку сменять на `get`?

**Comment by bageus** [comment]
да
