### ISSUE TITLE
Сортировка заданий проекта

### ISSUE THREAD

**Issue by hoolisoftware** [JUSTConnect/ursus-planet-client#218]
Сортировка будет работать следующим образом (убывающий приоритет):
- Статус задания
    - Get (получить награду)
    - Do it / Follow (которые можно выполнить)
    - Done (выполненные)
- Срочность задания (у которых expiration всплывают выше)
- Соц сеть задания (+ custom)
    - Сортируется по алфавиту (Discord, Github, Telegram, X)
    - Последними идут задачи custom

P.S. Может ещё по объёму награды сортировать как-то для удобства?

**Comment by bageus** [comment]
норм так как ты описал- по объему сортировать не нужно
есдинственное 
Get самый наивысший приоритет - 1
Do it/Follow (expiration = on) - 2
Do it/Follow (expiration = off) - 3
Done - 4

соцсеть - согласен по алфавиту
