### ISSUE TITLE
зачем эти груповые тиски

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#229]
![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/ecaaca41-2327-497b-903c-f90f0bbeee2e)

**Comment by hoolisoftware** [comment]
![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/64575343/0e3868a4-9cbe-49b1-8f92-f9f48154bbb1)



![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/64575343/f2a85c08-925c-4be8-87d1-27c08c70d857)

Групповые - это те которые выполняются в группах Telegram.

**Comment by bageus** [comment]
понятно

**Comment by hoolisoftware** [comment]
Удаляем?
