### ISSUE TITLE
отсутствует таска на сообщение

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#230]
![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/74f0d5c6-262a-4438-a9b5-a17e8a90d7f7)

**Comment by hoolisoftware** [comment]
![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/64575343/5901a781-8a96-4ff7-b7e2-31382b1e1428)
