### ISSUE TITLE
Сверстать модалку NFT

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#232]
при нажатии на NFT Wallet показывать модалку

![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/1f3c542c-9d53-41fd-8cfc-13da310570eb)

**Comment by bageus** [comment]
нужен белый ховер на cancel

![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/c472654a-c77a-4c59-8b76-f3243701661e)

**Comment by bageus** [comment]
и разные размеры

![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/5726d639-e284-465f-a275-25819c3a6250)

**Comment by hoolisoftware** [comment]
а что делать с разными размерами? обрезать подумал что не круто. и если и обрезать то каким образом (что бы занимала всю область, или что бы просто помещалась в область).

**Comment by bageus** [comment]
так а почему они разные ? должен быть один размер, нам же нужно просто картинку показать которую пользователь выберет в качестве аватара
