### ISSUE TITLE
Сверстать страницы More

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#233]
Mission:
- [Вкладка Mission](https://www.figma.com/file/wlyTRHU0YAsudasbktqay5/Ursus-planet-(Copy)?type=design&node-id=3904%3A5461&mode=design&t=68r2t9LLjJWduOOI-1)
- [Вкладка Problems](https://www.figma.com/file/wlyTRHU0YAsudasbktqay5/Ursus-planet-(Copy)?type=design&node-id=3904%3A5658&mode=design&t=68r2t9LLjJWduOOI-1)
- [Вкладка Solutions](https://www.figma.com/file/wlyTRHU0YAsudasbktqay5/Ursus-planet-(Copy)?type=design&node-id=3904%3A5858&mode=design&t=68r2t9LLjJWduOOI-1)

Docs:
- [Вкладка GitBook](https://www.figma.com/file/wlyTRHU0YAsudasbktqay5/Ursus-planet-(Copy)?type=design&node-id=3904%3A6888&mode=design&t=68r2t9LLjJWduOOI-1)
- [Вкладка Documents](https://www.figma.com/file/wlyTRHU0YAsudasbktqay5/Ursus-planet-(Copy)?type=design&node-id=3904%3A7295&mode=design&t=68r2t9LLjJWduOOI-1)

Careers:
- [Вкладка Careers](https://www.figma.com/file/wlyTRHU0YAsudasbktqay5/Ursus-planet-(Copy)?type=design&node-id=3904%3A6060&mode=design&t=68r2t9LLjJWduOOI-1)
- [Вкладка Vacancies без вакансий](https://www.figma.com/file/wlyTRHU0YAsudasbktqay5/Ursus-planet-(Copy)?type=design&node-id=3904%3A717&mode=design&t=68r2t9LLjJWduOOI-1)

Media:
- [Вкладка Media](https://www.figma.com/file/wlyTRHU0YAsudasbktqay5/Ursus-planet-(Copy)?type=design&node-id=3904%3A6257&mode=design&t=68r2t9LLjJWduOOI-1)

Support:
- [Вкладлка Support](https://www.figma.com/file/wlyTRHU0YAsudasbktqay5/Ursus-planet-(Copy)?type=design&node-id=3904%3A7083&mode=design&t=68r2t9LLjJWduOOI-1)/

Требования:
- Сверстать указанные страницы для десктоп и мобильных устройств
- Поставить ссылки
- На страницы могут попасть неавторизованные пользователи
- Отображать кол-во подписчиков на странице Media не нужно

**Comment by hoolisoftware** [comment]
# Генеральные вопросы

1) Что по поводу остальных вкладок?

Имеется ввиду:
- нужно ли делать только те вкладки которые вы выделили, или все?
- если не нужно делать вкладки которые вы не выделили, но нужно ли их кнопки показывать, или скрыть?

![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/64575343/ae4c2938-e02a-4612-b3e3-6bd9b50b3a3d)
![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/64575343/f2b73c46-f51c-43a1-bf6c-33aa5e604807)
![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/64575343/55fb41e0-3376-4720-9bf0-5017e9e380b5)

2) На эти страницы можно будет попасть через эти ссылки?

![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/64575343/4bdfe4be-feea-4ee7-9ead-564fe0bc592c)

**Comment by hoolisoftware** [comment]
# Вопросы по Docs / Gitbook

1) Куда ведут [эти кнопки](https://www.figma.com/file/wlyTRHU0YAsudasbktqay5/Ursus-planet-(Copy)?type=design&node-id=3904%3A6888&mode=design&t=I4nojHrFFADKdKh4-1)?

![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/64575343/0203a552-cd1c-44c2-a450-5df8e810d1df)

**Comment by hoolisoftware** [comment]
# Вопросы по Carrers / Careers

**1) Куда ведёт [эта кнопка](https://www.figma.com/file/wlyTRHU0YAsudasbktqay5/Ursus-planet-(Copy)?type=design&node-id=3904%3A6060&mode=design&t=I4nojHrFFADKdKh4-1)?**

![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/64575343/4d071b8e-578d-4cd4-b17d-29fc42ba8b37)

**Comment by hoolisoftware** [comment]
# Вопросы по Media / Media

1) Подразумевается что [эти карточки](https://www.figma.com/file/wlyTRHU0YAsudasbktqay5/Ursus-planet-(Copy)?type=design&node-id=3904%3A6257&mode=design&t=I4nojHrFFADKdKh4-1), не считая их ссылки будут статичными, т.е. вы не сможете добавлять новые медиа (например facebook которого там нет). Ссылки сможете редактировать в админке в настройках сайта. Верно?

![image](https://github.com/JUSTConnect/ursus-planet-client/assets/64575343/cb76ab49-3445-464f-8e96-e9d94557ef21)

**Comment by hoolisoftware** [comment]
# Вопросы по Support / Support

1) Куда ведут [эти кнопки](https://www.figma.com/file/wlyTRHU0YAsudasbktqay5/Ursus-planet-(Copy)?type=design&node-id=3904%3A7083&mode=design&t=I4nojHrFFADKdKh4-1) и ссылку Write by email?

![image](https://github.com/JUSTConnect/ursus-planet-client/assets/64575343/77f3a783-b292-4091-adea-570c865fffd6)
