### ISSUE TITLE
пропали все базовые ховеры

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#239]

**Comment by bageus** [comment]
как быть с белыми ховерами и синими? прямо сюда скидывать или отдельные задачи создавать?

**Comment by hoolisoftware** [comment]
а какая разница между ними, или под белыми вы имеете ввиду блинк анимацию?

**Comment by hoolisoftware** [comment]
я кстати не понимаю зачем кнопку cancel белым подсвечивать, моё мнение - выглядит не к месту. когда кнопка save и cancel по одинаковому анимированы...

**Comment by bageus** [comment]
ну  может ты и прав на cancel можно оставить базовый ховер а на остальных белый
