### ISSUE TITLE
перестала работать кнопка (раньше переносили в notification)

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#242]
![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/c40d60f6-d0af-4bbe-aac7-991ff4d6bb22)

**Comment by hoolisoftware** [comment]
Странно, но у меня кнопка работает, перепроверьте...

**Comment by hoolisoftware** [comment]
Или может я не так понял.
