### ISSUE TITLE
не пропадают тостеры + нужно наверное им крестик добавить для мгновенного закрытия

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#245]
![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/d75f6015-5f7f-428f-862e-8fbefa17e29d)

**Comment by hoolisoftware** [comment]
Теперь их можно закрывать при нажатии. Так как тостеры не предполагают никаких действий я думаю мы можем это позволить что бы не усложнять интерфейс.
