### ISSUE TITLE
чтобы избежать проблем при замене имени - предлагаю в реферальный код добавлять случайную комбинацию цифр или букв

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#249]
![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/6ee0a346-ec6e-457e-b02c-16e2fe420f36)

**Comment by hoolisoftware** [comment]
https://github.com/orgs/JUSTConnect/projects/1/views/1?pane=issue&itemId=54313283

Мы уже решили запрещать менять имя пользователя дважды. Но, если хотите можем забрать на след спринт это улучшение.

**Comment by bageus** [comment]
Ok
