### ISSUE TITLE
а таймер где будет?

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#252]
![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/36c7b2f0-683e-44f2-a8da-3c642b6b777b)

**Comment by hoolisoftware** [comment]
Внутри тултипа.

**Comment by bageus** [comment]
ok

**Comment by hoolisoftware** [comment]
вот как-то так, откройте патч посмотрите!



![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/64575343/494bc110-c494-4749-92d4-beac29858fba)
