### ISSUE TITLE
до и после подключения соц сетей

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#253]
до

![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/781d0013-c78b-42c9-a819-777e00a8e257)

после

![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/4c6d4f50-9d61-46aa-98ec-21c5703df456)

**Comment by hoolisoftware** [comment]
Можете подробнее описать проблему.

**Comment by bageus** [comment]
до подключения соцсетей текст на странице выглядит как на первом скрине, после подключения текст выглядит иначе

**Comment by hoolisoftware** [comment]
речь идёт о разных версиях. В текущей версии вроде ничего не меняется до и после подключения кроме нижнего плейсхолдера.

**Comment by hoolisoftware** [comment]
можете показать на текущей версии? что бы я понял о чём идёт речь. сравнение до и после + что не нравится.

**Comment by bageus** [comment]
в общем я понял в чем дело, там видимо переадресация стоит на прод когда подключаешь соцсетиь в спринте
вопрос снимается
