### ISSUE TITLE
ранше было лучше

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#256]
сейчас

![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/744fc803-bef5-4f2a-ad83-c19aed472731)

раньше

![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/009379f4-45a2-4160-9242-9dab3ae00675)

**Comment by hoolisoftware** [comment]
Проверьте ещё раз, у меня почему-то кнопки на на варианте 2 выглядят. Возможно у вас стили не сработали после патча.

**Comment by bageus** [comment]
иконки синими сделай в active

![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/ba4c7c23-8edf-4412-9440-cbb8a4d9e1b9)
