### ISSUE TITLE
в карточках встроена  прокрутка - нужно ее убрать

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#273]
![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/740380ad-a9d0-45af-88cc-bfe9512d69db)

**Comment by hoolisoftware** [comment]
Не вижу на скриншоте бара проткрутки, можете подробнее пояснить?

**Comment by bageus** [comment]
я не могу их словить на скрине, вот в этих двух есть прокрутки
