### ISSUE TITLE
добавить ссылки

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#277]
![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/50eb743c-5563-4f80-a25e-aec95395def7)

**Comment by hoolisoftware** [comment]
Можете сюда их прикрепить?

**Comment by bageus** [comment]
телеграм https://t.me/ursasplanet
дискорд - https://discord.gg/ursas
твиттер - https://twitter.com/UrsasPlanet
медиум - ursasplanet.medium.com
