### ISSUE TITLE
major - не пойму почему я не вижу страницу вместе с кнопками

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#39]
![Image](https://github.com/hoolisoftware/ursus-planet/assets/36338626/8bdef432-6ed2-4d97-b156-afe7501c1afe)

**Comment by hoolisoftware** [comment]
Не понятна правка

**Comment by bageus** [comment]
вот на скрине у меня открыта страница - наверное хотелось бы что бы я видел полностью кнопку, а то получается какая то незавершенная страница

**Comment by hoolisoftware** [comment]
Кстати с этим я тоже борюсь, тут нужно поэкспериментировать с отступами

**Comment by bageus** [comment]
так а что мне тут нужно ответить? ты написал что есть проблемка - скорее всего из-за отступов

**Comment by hoolisoftware** [comment]
Я имею ввиду что это проблема общая а не локальная, её нужно фиксить через ограничения размера карточки, что требует больших переделок в лайауте страницы, иначе придётся каждый раз сталкиваться с этой проблемой на схожих страницах

**Comment by hoolisoftware** [comment]
Лучше оставить на следующий этап, т.к. это скорее всего не мажор учитывая объёмность задачи

**Comment by bageus** [comment]
а размеры верные везде ты задал?

**Comment by hoolisoftware** [comment]
Пока что да, скорее всего они и будут разные в некоторых страницах

**Comment by hoolisoftware** [comment]
Нужно обсудить как поступить. Задача может как затянуться так и оказаться простой.
