### ISSUE TITLE
next - point system - привязать систему поинтов к интерфейсу

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#57]
рядом с короной пока отображаем 0 или 3 точки рядом со звездочкой отображаем кол-во поинтов начальное значение 0

![Image](https://github.com/hoolisoftware/ursus-planet/assets/36338626/451189bc-d0e7-44d8-8652-187d6c57b1da)

**Comment by hoolisoftware** [comment]
Предлагается добавить в бекенд пользователю свойство - баллы, и оттуда отображать.

**Comment by bageus** [comment]
хорошо
