### ISSUE TITLE
next - генерировать  разные базовые изображения профиля

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#60]
![Image](https://github.com/hoolisoftware/ursus-planet/assets/36338626/0fbb6a23-487c-4906-94e2-9e247c6903ad)

**Comment by hoolisoftware** [comment]
Для этого требуется в бекенде прописать логику их генерации?

**Comment by bageus** [comment]
что на счет исключить черный и белый из цветов для компиляции?
![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/f2591b34-9099-4273-b4a5-cba0633aba4a)
