### ISSUE TITLE
major - не выполен этот дропдаун

### ISSUE THREAD

**Issue by bageus** [JUSTConnect/ursus-planet-client#70]
открывается при нажатии на 

![Image](https://github.com/hoolisoftware/ursus-planet/assets/36338626/24b5ea9a-e27c-4432-8e63-a604f5340151)

**Comment by bageus** [comment]
при нажатии переносит в настройки notification

![Image](https://github.com/JUSTConnect/ursus-planet-client/assets/36338626/cbf31766-b768-4093-a623-0274e25ee2e9)

**Comment by hoolisoftware** [comment]
А куда должно переносить, или никуда не должно?

**Comment by hoolisoftware** [comment]
Так оно итак переносит не?
